# Generated by Django 5.1.4 on 2024-12-09 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_alter_post_created_at_alter_topic_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='last_updated',
            field=models.DateTimeField(null=True),
        ),
    ]
